export interface Excel {
    razaoSocial: string,
    CNPJ: string,
    naturezaPJ: string,
    cep: string,
    Telefone: string,
    emailInstitucional: string,
    dataAssociacao: string,
    dataEncerramento: string,
    presidente: string,
    CPF: string,
    email: string,
    celular: string,
    missao: string,
    destaquePrioritarias: string,
    profissionaisCLT: string,
    voluntarios: string,
    possuiConselho: string,
    ajudaPaciente: string,
    possuiAssentoConselhoOuInstancia: string,
    temClarezaProposito: string,
    conhecimentoTecnicoEntidade: string,
    relacionamentoDiferente: string,
    discursoPautado: string,
    defendeIdeiasEProjetos: string,
    projetosEstruturados: string,
    sistematizacaoEstruturada: string,
    discursoPlanejamentoPrazos: string,
    TelefoneFixo: string

    }